Android compatability fixes
robinpowered/react-native-device-info pull request #10
Opened 2017-01-26 17:15 UTC by ajwhite

🔔  **Shame** 🔔 

I had not tested this on android, totally overlooked.

This fixes a number of issues, didn't realize my IDE wasn't showing my any warnings because it couldn't find any project deps. After working within the proper environment, I've cleaned this up to a working state.

### Changes

#### Dependency removal
Removed `com.google.android.gms:play-services-gcm:+` for now. This was conflicting with our primary dependencies causing libraries to become unavailable. **It was only used for `instanceId`**, which we do not need.

#### React error
The `@ReactMethod` was getting a `ReadableMap` when calling `getMap` on the `WritableMap`. This lead to exceptions in React Native as it must be a `WritableMap`, and casting it as such didn't seem to do the trick. 

Now `getWritableConstantsMap` produces a flat map of the values. `getConstants` will use this and embed it inside a `HashMap` containing a root node, with the key `DeviceInfo`. The `@ReactMethod` will simply use the `WritableNativeMap` result from `getWritableConstantsMap` and resolve the `Promise`.

2017-01-28 00:02 UTC, christophermark requested changes

2017-01-28 00:02 UTC, christophermark commented on android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
> +    constants.putString("buildVersion", "not availalble");
Typo intentional?

2017-01-28 00:02 UTC, christophermark commented on android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
> +      e.printStackTrace();;
🔥

2017-01-28 17:22 UTC, ajwhite commented
Good catches, cleaned up

2017-01-30 14:29 UTC, christophermark commented
The changes before would have broken the build - is this fully tested working?

2017-01-30 17:00 UTC, ajwhite commented
Two semi colons are actually [IDE warnings, rather than compiler errors](http://stackoverflow.com/questions/7571007/compiler-doesnt-complain-when-i-ended-a-line-with-two-semicolons-why). Must have missed the IDE warning, but the previous build compiled and worked as expected.

Went through again for good measure with the latest changes, all is working well.

2017-01-31 16:06 UTC, christophermark approved these changes
👍

2017-01-31 16:06 UTC, merged